#! /usr/bin/bash
# stash the original font and store the game font.
terminal_font=$(gsettings get org.gnome.desktop.interface monospace-font-name)
game_font='square 13'

echo "- your previous terminal font was $terminal_font"
echo "- to recover previous font, in case of any crash from the game, please run"
echo "gsettings set org.gnome.desktop.interface monospace-font-name "$terminal_font""

if [[ $(fc-list | grep -c square) == 0 ]];
  then  echo "square.ttf not found.";
        echo "please install the square font (available at https://strlen.com/square/) inside /usr/share/fonts, /usr/local/share/fonts or ~/.fonts";
  else  gsettings set org.gnome.desktop.interface monospace-font-name "$game_font";
        python $(dirname "$0")/src/main.py;
        gsettings set org.gnome.desktop.interface monospace-font-name "$terminal_font";
fi
